.\" $Header: /home/amb/CVS/procmeter3/man/procmeter3.1,v 1.7 1999-07-28 19:55:06 amb Exp $
.\"
.\"  ProcMeter - A system monitoring program for Linux.
.\"
.\"  Manual page for procmeter program (v3.1c).
.\"
.\"  Written by Andrew M. Bishop
.\"
.\"  This file Copyright 1998,99 Andrew M. Bishop
.\"  It may be distributed under the GNU Public License, version 2, or
.\"  any higher version.  See section COPYING of the GNU Public license
.\"  for conditions under which this file may be redistributed.
.\"
.TH PROCMETER3 1 "July 28, 1999"

.SH NAME

procmeter3 \- A user friendly system monitoring program.

.SH SYNOPSIS

.B procmeter3
.I [\-h]
.I [...]
.I [X \ windows \ options]

.SH DESCRIPTION

.I ProcMeter
displays one or more pieces of information about the operating system and other
resources.  Most of the information that is displayed comes from the /proc
filesystem.  The program is modular and very configurable.

.SH OPTIONS

The command line options are described below.
.TP
.BR \-h
Provides a help message listing the available outputs.  This will be different
for different computers depending on the Linux kernel version that is being used
and the hardware/software that is configured.
.TP
.BR ...
A list of names of outputs that are to be displayed.  This can include any of
the outputs that are available (see the -h option).  For the CPU usage is in a
module named
.B Statistics
with an output named
.B CPU
and there are graph and text options.  To display the CPU usage graph you would
use the command line option
.B Statistics.CPU-g
.TP
.BR X \ windows \ options
The standard set of X Windows program options, see X(1) for information.  These
include
.B -geometry
to set the size of the window,
.B -display
to set the display and other general X window options.

.SH USAGE

When started the program will display all of the requested information in a set
of output panels (vertically aligned by default).  Each output can be either a
graph or text, and can have a label indicating what it represents.  The outputs
that are displayed are those from the command line and those from the
.B .procmeterrc
configuration file.
.LP
The left mouse button will produce a menu of options that are specific to the
output that is selected.  The
.B Properties
option on this menu will give more detailed information about the origin and
meaning of the information that is displayed.  When the properties information
window is displayed, clicking on another output will change the displayed
information.  The
.B Move to Above
and 
.B Move to Below
options allow the output to be moved around in the window.  Selecting one of
these options will change the mouse cursor to a hand, use this to select another
output.  The output that was selected first will be moved to above or below the
output that was selected second.  The
.B Run
option on the menu (which may not be available on all outputs) will run the
specified command.  This may be to display a list of running processes, show the
amount of free memory or disk space for example.  This menu option is
configurable in the
.B .procmeterrc
file.
.LP
The right mouse button will produce a set of menus that list the modules that
are available and for each of them the available set of outputs.  There are two
types of output, text and graphical, these are indicated in the sub-menus by
icons to the right of the name in the sub-menu.  Selecting one of the outputs
from a sub-menu will cause that output to be displayed if it is not already
visible.  If it is currently displayed then it will be disabled.  Those that are
currently displayed are indicated by a marker to the left of the name in the
sub-menu.  When the output is added to the window it will be placed at the
bottom, use the left mouse button to move it if required.
.LP
The middle mouse button will display the sub-menu that is associated with the
module for the output that is selected.  This is one of sub-menus that are found
with the right mouse button.

.SH MODULES

The modules that are provided with the program are the following:
.TP
.BR APM
Advanced Power Management information.  These outputs are only available if you
have configured the Linux kernel to have the APM feature and you have the
appropriate hardware.  The outputs can tell you the amount of time remaining and
the state of charge of the battery.
.TP
.BR Biff
Monitors the e-mail inbox (in
.B /var/spool/mail/<username>
or
.B /var/mail/<username>
) and indicates the number of e-mails that are waiting and the size of the
inbox.  The
.I options
parameter in the
.B .procmeterrc
file can be used to specify an alternate filename to use for the inbox.
.TP
.BR Date_Time
The current date and time and the amount of time since the system was last
booted.  Different outputs are available that allow the format of the date and
time information to be changed.
.TP
.BR DiskUsage
Shows the percentage of the disk that is used and the amount of free space for
each of the local disks that it finds are mounted or can be mounted when the
program starts.  Extra disks can be passed as options using the
.I options
parameter in the
.B .procmeterrc
file to contain a space separated list of mount points.
.TP
.BR LogFile
Monitors the size and number of lines and the rate of increase of the size or
number of lines in a set of log files.  The
.I options
parameter in the
.B .procmeterrc
file contains a space separated list of log file names.
.TP
.BR Memory
The amount of memory that is used for programs, buffers, cache and the amount
that is free.  This is the same information that is available from the
.B free
program, but is available here as a graph or as text.
.TP
.BR Network
The network devices and the amount of traffic on each of them.  It will
automatically pick up available devices when it starts.  To specify others use
the
.I options
parameter in the
.B .procmeterrc
configuration file which is a space separated list of device names.
.TP
.BR Processes
The load average and the number of processes running and starting.
.TP
.BR ProcMeter
Information about the procmeter program itself.
.TP
.BR Sensors
Hardware sensors for temperature and fan speed.  (Requires lm78 hardware and
kernel patch from http://www.netroedge.com/~lm78/).
.TP
.BR Statistics
Low level system statistics.  For example CPU usage, disk usage, swapping and
paging.
.TP
.BR Stat-CPU
More detailed statistics about individual CPU usage including support for SMP
machines.
.TP
.BR Stat-Disk
More detailed statistics about individual disk usage including support for up to
4 disks.  (This limit is set by the kernel and not by procmeter.)
.TP
.BR Stat-Intr
More detailed statistics about individual interrupts including support for up to
32 interrupts (more interrupts are available from the kernel but not displayed).
.TP
.BR Uname
The system information, hostname and Linux kernel version, the same as the
output of the
.B uname
program.
.TP

.SH X RESOURCES

As with all X Window programs X resources can be used.  For this version of
ProcMeter (compared to previous versions) this is not the default method of
configuring the program.  The file $HOME/.procmeterrc contains the configuration
information.

.SH SEE ALSO

X(1) procmeterrc(5)
.LP
biff(1) free(1) uname(1)

.SH AUTHOR

Andrew M. Bishop 1998,99
